#!/bin/bash
#
# by stef@dev2ops.eu
# June 2017
# setup the kubernetes cluster on all nodes : master(s) and node(s)
#
# param1 : cluster_name

if [ "$#" -ne 1 ]; then
 echo "Usage: $0 cluster_name"
 exit 1
fi

cluster_name=$1

wd=$DEVOPS_AWS
ansible=$DEVOPS_ANSIBLE
log_date=`$wd/utils/getFormatDate.sh`
log_file=$kubernetes_cluster_name"_log_"$log_date

# wait the cluster until up and running
$wd/utils/waitCluster.sh kubernetes $cluster_name

# unlock root to exec ansible
# the file with instance private IP is the dedicated directory
echo -n "unlocking ssh on nodes ..."
$wd/utils/unlockRoot_kubernetes.sh $cluster_name > $DEVOPS_LOGS/$log_file
echo " done"

# install ansible package on each instance

# exec kubernetes ansible playbook to setup kubernetes on all nodes
echo "playing ansible playbooks (this could take a while!) ..."
cd $ansible/kube/scripts
./deploy-cluster.sh $cluster_name $DEVOPS_LOGS/$log_file
echo " done"

# get the first master in the host list for query
master=`cat $ansible/kube/inventory/hosts_kube_$cluster_name | grep -A 1 master | egrep -v master | awk -F "\"" '{print $2}'`

# display the status of the kubernetes cluster
ssh $master 'kubectl cluster-info ' | tee -a $DEVOPS_LOGS/$log_file
ssh $master 'kubectl get node ' | tee -a $DEVOPS_LOGS/$log_file
ssh $master 'kubectl get all --all-namespaces ' | tee -a $DEVOPS_LOGS/$log_file

for i in `seq 1 3`
do
	sleep 5
	$wd/utils/showClusterStatus.sh $cluster_name
done
