#!/bin/bash
# by stef@dev2ops.eu
# November 2017
# create the infra as code in AWS for a new Base Documentaire Infra
# 

if [ "$#" -ne 1 ]; then
 echo "Usage: $0 project_name"
 exit 1
fi

project_name=$1

wd=/root/devel/automation/asCode/aws/scripts


echo -n "creating the Base Documentaire machine(s) as project : $project_name ... "

# test if project exists, if yes we do nothing
#exist=`$wd/utils/existCluster.sh swarm $cluster_name`
#if [ "$exist" == "yes" ]
#then
#	echo "sorry this cluster already exists !!!"
#	exit 0
#fi



$wd/sub/create_base_doc.sh $project_name

echo "done"
