# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
items:
- apiVersion: v1
  kind: Template
  labels:
    template: devops-app-template
  message: Welcome to devops app template 
  metadata:
    annotations:
      description: |-
        This template generates an app into a JBoss container.
        NOTE: the app must be accessed via an Apache container. Oracle database connector already configured 
      iconClass: icon-devops
      openshift.io/display-name: Devops App (in JBoss) 
      tags: devops,app
      template.openshift.io/documentation-url: https://www.dev2ops.eu/devops/openshift/templates/app.html
      template.openshift.io/long-description: This template deployes a Jboss container with one or more war files. 
        You must modify the Dockerfile. Image based on JBoss image, based on Centos 7.1 
      template.openshift.io/provider-display-name: devops.eu 
      template.openshift.io/support-url: https://www.dev2ops.eu/support.html
    name: devops-app
    namespace: devops
    resourceVersion: "1"

  objects:

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: devops-${APP_SERVICE_NAME}
      name: devops-${APP_SERVICE_NAME}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_SERVICE_NAME}:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: ${APP_SERVICE_NAME}
        git:
          uri: https://github.com/scampagna/openshift-apps.git
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jboss:latest
            namespace: devops
        type: Docker
      triggers:
      - github:
          secret: fPOAylwM4IWxWdbrUMGb
        type: GitHub
      - generic:
          secret: oQqyHHviSmnjm3ow6b4K
        type: Generic
      - type: ConfigChange
      - imageChange: {}
        type: ImageChange
    status:
      lastVersion: 0
    
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: ${APP_SERVICE_NAME}
      name: ${APP_SERVICE_NAME}
    spec: {}
    status:
      dockerImageRepository: ""

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      generation: 1
      labels:
        app: ${APP_SERVICE_NAME}
      name: ${APP_SERVICE_NAME}
    spec:
      replicas: 1
      selector:
        app: ${APP_SERVICE_NAME}
        deploymentconfig: ${APP_SERVICE_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            app: ${APP_SERVICE_NAME}
            deploymentconfig: ${APP_SERVICE_NAME}
        spec:
          containers:
          - image: 172.30.11.60:5000/devops/${APP_SERVICE_NAME}@sha256:9be736d0cf2d9f214780dfc9659ed9fac4484dd869e786e495af54e545ba4356
            imagePullPolicy: Always
            name: ${APP_SERVICE_NAME}
            ports:
            - containerPort: 8009
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${APP_SERVICE_NAME}
          from:
            kind: ImageStreamTag
            name: ${APP_SERVICE_NAME}:latest
            namespace: devops
        type: ImageChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0

  - apiVersion: v1
    kind: Service 
    metadata:
      name: ${APP_SERVICE_NAME} 
      namespace: devops
      labels: 
        app: ${APP_SERVICE_NAME} 
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:   
      ports:  
        - name: 8009-tcp
          protocol: TCP
          port: 8009
          targetPort: 8009
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: 8090-tcp
          protocol: TCP
          port: 8090
          targetPort: 8090
      selector:
        app: ${APP_SERVICE_NAME} 
        deploymentconfig: ${APP_SERVICE_NAME} 
      type: ClusterIP
      sessionAffinity: None
    status: 
      loadBalancer: {}

  parameters:
  - description: The name of the app Service exposed for the app container.
    displayName: app Service Name
    name: APP_SERVICE_NAME
    value: new-app
kind: List
metadata: {}
