#!/bin/bash
# by stef@dev2ops.eu
# June 2017
# create the infra as code in AWS for a new Docker Swarm cluster
# 

if [ "$#" -ne 3 ]; then
 echo "Usage: $0 cluster_name nb_manager(s) nb_worker(s)"
 exit 1
fi

cluster_name=$1
nbManagers=$2
nbWorkers=$3

wd=$DEVOPS_AWS
ansible=$DEVOPS_ANSIBLE
host_file=$ansible/inventories/hosts_swarm_$cluster_name


echo -n "creating the Docker Swarm cluster : $cluster_name ... "

# test if cluster exists, if yes we do nothing
exist=`$wd/utils/existCluster.sh swarm $cluster_name`
if [ "$exist" == "yes" ]
then
	echo "sorry this cluster already exists !!!"
	exit 0
fi


echo "[manager]" > $host_file

for i in `$wd/sub/create_swarm_manager.sh $cluster_name $nbManagers`
do
	echo $i >> $host_file
done

echo "[worker]" >> $host_file
for i in `$wd/sub/create_swarm_workers.sh $cluster_name $nbWorkers`
do
	echo $i >> $host_file
done
echo "done"
