---
# This playbook deploys all components for 'base documentaire'

- hosts: localhost 

  roles:
# REDIS 3.2.16
    - geerlingguy.redis

- hosts: localhost
  roles:
# SOLR 4.x
    - geerlingguy.java
    - geerlingguy.solr

- hosts: localhost
  pre_tasks:
    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql57-community-release-el7-7.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"

  roles:
# LAMP , MySQL 5.7, Apache 2.4.6 , PHP 5.4.16
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php

# Drupal 7.56
    - geerlingguy.drush
    - geerlingguy.composer
    - geerlingguy.drupal

- hosts: localhost
  roles:
# Tomcat 8
    - sonodar.oracle-jdk8
    - sonodar.tomcat8


